import Head from 'next/head'
import Link from "next/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Builds Test Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Pages
        </h1>

        <ul>
          <li>
            <Link href="/experiences">
              <a>Experiences</a>
            </Link>
          </li>
          <li></li>
        </ul>



      </main>
    </div>
  )
}
